name: proj_flutter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - producao.env
    - local.env
    - assets/img/pipedrive_icon.png
    - assets/img/conciliadora_icon.jpeg

  fonts:
     - family: PlusJakartaSans
       fonts:
         - asset: assets/fonte/PlusJakartaSans.ttf
